# I stole this from Scott and haven't tested it yet. -Evans
version: "3.9"
services:
  web:
    build: . 
    ports:
      - "5000:5000"
    networks:
      - star-net
    environment:
        - REACT_APP_FEATURED_ELECTIONS=''
        - REACT_APP_MAX_BALLOT_RANKS=10
        - REACT_APP_DEFAULT_BALLOT_RANKS=6
        - REACT_APP_BACKEND_URL=http://localhost:5000
        - REACT_APP_KEYCLOAK_URL=http://localhost:8080/realms/Dev/protocol/openid-connect
        - DANGEROUSLY_DISABLE_HOST_CHECK=true
        - FRONTEND_PORT=5000
        - DATABASE_URL=postgresql://postgres:ChangeMeOrDontTest2020@my-db:5432/postgres
        - DEV_DATABASE=FALSE
        - KEYCLOAK_SECRET=DefaultKeycloakSecret
        - KEYCLOAK_URL=http://keycloak:8080/realms/Dev/protocol/openid-connect
        - CLASSIC_ELECTION_COUNT=0
        - CLASSIC_VOTE_COUNT=0
        - SENDGRID_API_KEY='SG.<insert api key>' 
        - SENDGRID_GROUP_ID='<insert group id>'
        - EMAIL_TEST_MODE=if defined will prevent emails from being sent from email service while testing
        - FROM_EMAIL_ADDRESS=elections@star.vote
    depends_on: 
      - my-db
      - keycloak

  my-db:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - star-net
    environment:
      - POSTGRES_PASSWORD=ChangeMeOrDontTest2020
    restart:
      always

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm
    ports:
      - '8080:8080'
    networks:
      - star-net
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    restart:
      always
networks:
  star-net: {}
