name: Build, push, and deploy

on:
  push:

    # Testing with the 260 branch right now.
    #branches: [ $default-branch ]
    branches: [ 260-build-and-deploy-docker-container-image ]

#permissions:
#  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
#    permissions:
#      packages: write
    steps:
#      - uses: actions/checkout@v3.5.2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4.0.0
        with:
          push: true
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
#          file: ./Dockerfile

  # Based on https://stackoverflow.com/questions/57921401/push-to-origin-from-github-action/58393457#58393457
  # Trying to do proper gitops IaC here. This will checkout the
  # star-server-infra repo, update the image tag variable, then commit those
  # changes. After that, the star-server-infra repo should have a pipeline that
  # automatically deploys it to the dev env.
  # Commented out for now, because it's not working.
      - uses: actions/checkout@v3
        with:
          repository: 'Equal-Vote/star-server-infra'
      - name: Updates the star-server image tag in the star-server-infra repo.
        run: sed -i "s#ghcr.io/${{ env.REPO }}:.*#ghcr.io/${{ env.REPO }}:${{ github.sha }}#" dev/variables.tf 
      - name: Commit report
        run: |
          git config --global user.name 'star-server-bot'
          git config --global user.email 'noreply@equal.vote'
          git commit -am "Automatically updating star-server image."
          git push
