name: Build, push, and deploy
on:
  push:

    # Testing with the 260 branch right now.
    #branches: [ $default-branch ]
    branches: [ 260-build-and-deploy-docker-container-image ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      # We have to do this to workaround these errors:
      # ERROR: failed to configure registry cache importer: invalid reference format: repository name must be lowercase
      - name: Creating REPO var that contains lowercase repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ env.REPO }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=schedule
            type=sha,format=long
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      - name: Log in to GitHub container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v4.0.0
        with:
          cache-from: type=registry,ref=ghcr.io/${{ env.REPO }}:${{ github.ref_name }}
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - uses: actions/checkout@v3
        with:
          repository: 'Equal-Vote/star-server-infra'
          token: ${{ secrets.GH_PAT }}
      - name: Update variables.tf with new container tag
        run: |
          sed -i "s#\"ghcr.io/${{ env.REPO }}:.*#\"ghcr.io/${{ env.REPO }}:${{ github.sha }}\"#" variables.tf
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Automatically updating star-server image."
          git push
