name: Build, push, and deploy

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Metadata action
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

          # Using `branch` to give a predictable name to cache from, and using
          # `sha` so we always have a unique tag which will trigger
          # star-server-infra terraform to run.
          tags: |
            type=ref,event=branch
            type=sha

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          cache-to: type=inline
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      # TODO: Currently using a personal access token to do this, which is not
      # secure. Need to switch to switch to one of these maybe?
      # 
      # * https://github.com/marketplace/actions/workflow-dispatch
      # * https://github.com/marketplace/actions/trigger-workflow-and-wait
      #
      # Deploy to star.sandbox.star.vote (argocd Kubernetes)
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'Equal-Vote/argocd'
          token: ${{ secrets.GH_PAT }}
      - name: Update argocd repo
        run: |
          yq -i ".image.tag = \"sha-${GITHUB_SHA::7}\"" applications/star-server/values.yaml
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "Automatically updating bettervoting image."
          git push
