name: Docker Compose Action

on: [push]

jobs:
  test:
    permissions:     
      pull-requests: write
      id-token: write
      contents: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        continue-on-error: false

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version
        continue-on-error: false

      - name: Start application-specific services using Docker Compose
        run: docker compose up --build playwright
        continue-on-error: false

      - name: Check for failure
        id: tests
        run: |
            export status=$(grep -q "passed" ./testing/test-results/.last-run.json && echo passed || echo failed)
            echo "status=$status" >> "$GITHUB_OUTPUT"
            echo $status
  

      - name: Setup Pages
        if: steps.tests.outputs.status == 'failed'
        uses: actions/configure-pages@v5

      - name: Upload Artifact
        # id: deployment
        if: steps.tests.outputs.status == 'failed'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./testing/playwright-report/"
          retention-days: 30
    
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Fail the job if there any failed case
        if: steps.tests.outputs.status == 'failed'
        run : |
            echo "Tests failed. Please check the report at ${{ steps.deployment.outputs.page_url }}"
            exit 1
      
      
      - name: Stop Docker Compose services
        if: always()
        run: docker-compose down --volumes --remove-orphans
        continue-on-error: false

      
