name: Docker Compose Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run docker compose
        uses: adambirds/docker-compose-action@v1.5.0
        with:
          compose-file: "./docker-compose.yml"
          up-flags: "--build"
          test-container: "test-container"
          test-command: "npx playwright test"

      # - name: Execute tests in the running services
      #   run: |
      #     docker compose exec test-app pytest
